on:
  push:
    tags:
      - 'v*'
jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: slack-notify-release-action
        uses: italia/slack-notify-release-action@v0.3.0
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: C05D0D54KFD
          project_name: Trios Desktop app develop
