# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    # tags:
    #   - 'v*'
jobs:
  examplejob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Notify new release on Slack
        uses: italia/slack-notify-release-action@v0.4.0
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: C05D0D54KFD
          project_name: Slack notification action
